FROM python:3.9
WORKDIR /usr/src/app

RUN apt-get update \
  && apt-get -y install netcat gcc \
  && apt-get clean

RUN pip install --upgrade pip

COPY ./requirements-depl.txt .
RUN pip install -r requirements-depl.txt

COPY . .

CMD gunicorn -w 3 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT
